stages:
  - build
  - test
  - deploy

fisheye-job:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  before_script:
    - apt-get update && apt-get install -y curl 
  script: 
    - echo "Triggering Fisheye hook"
    - |
        curl -X PUT -H 'X-Api-Key: $FISHEYE_KEY' -H "Content-Type: application/json" -m 20 http://fisheye.openacs.org/rest-service-fecru/admin/repositories/nsf/incremental-index
