#!/usr/bin/env tclsh
#
# Add NSF printf-format attributes to declarations generated by
# genStubs.tcl. The script is idempotent and supports Tcl 8.5+.
#
# Usage:
#   tclsh add-format-attributes.tcl path/to/nsfDecls.h ...
#

if {[llength $argv] == 0} {
    puts stderr "usage: $argv0 nsfDecls.h ?nsfDecls.h ...?"
    exit 2
}

#
# Include both exported function names and NsfStubs member names.
#
array set formats {
    NsfDStringVPrintf  {printf, 2, 0}
    NsfPrintError      {printf, 2, 3}
    NsfLog             {printf, 3, 4}
    Nsf_DStringPrintf  {printf, 2, 3}

    nsfDStringVPrintf  {printf, 2, 0}
    nsfPrintError      {printf, 2, 3}
    nsfLog             {printf, 3, 4}
    nsf_DStringPrintf  {printf, 2, 3}
}

proc declarationName {line} {
    global formats

    foreach name [array names formats] {
        #
        # Exported declaration:
        #
        #   EXTERN int NsfPrintError(...);
        #
        set functionPattern [format \
            {(^|[[:space:]])%s[[:space:]]*\(} $name]

        #
        # Stub-table member:
        #
        #   int (*nsfPrintError)(...);
        #
        set memberPattern [format \
            {\(\*%s\)[[:space:]]*\(} $name]

        if {[regexp -- $functionPattern $line]
                || [regexp -- $memberPattern $line]} {
            return $name
        }
    }

    return ""
}

proc processFile {path} {
    global formats

    if {![file exists $path]} {
        error "file does not exist: $path"
    }

    set F [open $path r]
    fconfigure $F -translation binary
    set input [read $F]
    close $F

    array set found {}
    foreach name [array names formats] {
        set found($name) 0
    }

    set outputLines {}
    set declarationLines {}
    set activeName ""

    foreach line [split $input "\n"] {
        if {$activeName eq ""} {
            set activeName [declarationName $line]

            if {$activeName eq ""} {
                lappend outputLines $line
                continue
            }

            set declarationLines [list $line]
        } else {
            lappend declarationLines $line
        }

        #
        # Generated declarations may span multiple lines. Accumulate
        # through the first line containing their terminating semicolon.
        #
        if {[string first ";" $line] < 0} {
            continue
        }

        set declaration [join $declarationLines "\n"]
        incr found($activeName)

        if {[string first "NSF_attribute_format" $declaration] < 0} {
            set attribute \
                " NSF_attribute_format(($formats($activeName)));"

            #
            # There are no earlier semicolons in a generated function
            # declaration, so replacing the first one is sufficient.
            #
            if {![regsub -- {;} $declaration $attribute declaration]} {
                error "could not annotate $activeName in $path"
            }
        }

        foreach declarationLine [split $declaration "\n"] {
            lappend outputLines $declarationLine
        }

        set declarationLines {}
        set activeName ""
    }

    if {$activeName ne ""} {
        error "unterminated declaration for $activeName in $path"
    }

    foreach name [lsort [array names formats]] {
        if {$found($name) != 1} {
            error "expected one declaration of $name in $path, found $found($name)"
        }
    }

    set output [join $outputLines "\n"]

    if {$output eq $input} {
        puts "$path: already up to date"
        return
    }

    #
    # Write alongside the destination and rename atomically.
    #
    set temporary "${path}.tmp.[pid]"

    set code [catch {
        set F [open $temporary w]
        fconfigure $F -translation binary
        puts -nonewline $F $output
        close $F
        file rename -force $temporary $path
    } message]

    if {$code != 0} {
        catch {close $F}
        catch {file delete -force $temporary}
        error $message
    }

    puts "$path: added format attributes"
}

foreach path $argv {
    if {[catch {processFile $path} message]} {
        puts stderr "$argv0: $message"
        exit 1
    }
}
