/*
 * nsfDecls.h --
 *
 *	Declarations of functions in the platform independent public XOTcl API.
 *
 *  Copyright (C) 1999-2008 Gustaf Neumann, Uwe Zdun
 *
 * See the file "tcl-license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#ifndef _XOTCLDECLS
#define _XOTCLDECLS

/*
 * WARNING: This file is automatically generated by the tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the nsf.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */

#ifndef Nsf_Init_TCL_DECLARED
#define Nsf_Init_TCL_DECLARED
/* 0 */
EXTERN int		Nsf_Init(Tcl_Interp *interp);
#endif
/* Slot 1 is reserved */
#ifndef NsfIsClass_TCL_DECLARED
#define NsfIsClass_TCL_DECLARED
/* 2 */
EXTERN struct Nsf_Class * NsfIsClass(Tcl_Interp *interp, ClientData cd);
#endif
/* Slot 3 is reserved */
#ifndef NsfGetObject_TCL_DECLARED
#define NsfGetObject_TCL_DECLARED
/* 4 */
EXTERN struct Nsf_Object * NsfGetObject(Tcl_Interp *interp,
				CONST char *name);
#endif
#ifndef NsfGetClass_TCL_DECLARED
#define NsfGetClass_TCL_DECLARED
/* 5 */
EXTERN struct Nsf_Class * NsfGetClass(Tcl_Interp *interp,
				CONST char *name);
#endif
#ifndef NsfCreateObject_TCL_DECLARED
#define NsfCreateObject_TCL_DECLARED
/* 6 */
EXTERN int		NsfCreateObject(Tcl_Interp *interp, Tcl_Obj *name,
				struct Nsf_Class *cl);
#endif
/* Slot 7 is reserved */
/* Slot 8 is reserved */
#ifndef NsfDeleteObject_TCL_DECLARED
#define NsfDeleteObject_TCL_DECLARED
/* 9 */
EXTERN int		NsfDeleteObject(Tcl_Interp *interp,
				struct Nsf_Object *obj);
#endif
/* Slot 10 is reserved */
/* Slot 11 is reserved */
/* Slot 12 is reserved */
#ifndef NsfRemoveObjectMethod_TCL_DECLARED
#define NsfRemoveObjectMethod_TCL_DECLARED
/* 13 */
EXTERN int		NsfRemoveObjectMethod(Tcl_Interp *interp,
				struct Nsf_Object *obj, CONST char *nm);
#endif
#ifndef NsfRemoveClassMethod_TCL_DECLARED
#define NsfRemoveClassMethod_TCL_DECLARED
/* 14 */
EXTERN int		NsfRemoveClassMethod(Tcl_Interp *interp,
				struct Nsf_Class *cl, CONST char *nm);
#endif
#ifndef NsfOSetInstVar_TCL_DECLARED
#define NsfOSetInstVar_TCL_DECLARED
/* 15 */
EXTERN Tcl_Obj *	NsfOSetInstVar(struct Nsf_Object *obj,
				Tcl_Interp *interp, Tcl_Obj *name,
				Tcl_Obj *value, int flgs);
#endif
#ifndef NsfOGetInstVar_TCL_DECLARED
#define NsfOGetInstVar_TCL_DECLARED
/* 16 */
EXTERN Tcl_Obj *	NsfOGetInstVar(struct Nsf_Object *obj,
				Tcl_Interp *interp, Tcl_Obj *name, int flgs);
#endif
/* Slot 17 is reserved */
/* Slot 18 is reserved */
#ifndef Nsf_ObjSetVar2_TCL_DECLARED
#define Nsf_ObjSetVar2_TCL_DECLARED
/* 19 */
EXTERN Tcl_Obj *	Nsf_ObjSetVar2(struct Nsf_Object *obj,
				Tcl_Interp *interp, Tcl_Obj *name1,
				Tcl_Obj *name2, Tcl_Obj *value, int flgs);
#endif
#ifndef Nsf_ObjGetVar2_TCL_DECLARED
#define Nsf_ObjGetVar2_TCL_DECLARED
/* 20 */
EXTERN Tcl_Obj *	Nsf_ObjGetVar2(struct Nsf_Object *obj,
				Tcl_Interp *interp, Tcl_Obj *name1,
				Tcl_Obj *name2, int flgs);
#endif
#ifndef NsfUnsetInstVar2_TCL_DECLARED
#define NsfUnsetInstVar2_TCL_DECLARED
/* 21 */
EXTERN int		NsfUnsetInstVar2(struct Nsf_Object *obj,
				Tcl_Interp *interp, CONST char *name1,
				CONST char *name2, int flgs);
#endif
/* Slot 22 is reserved */
#ifndef NsfErrMsg_TCL_DECLARED
#define NsfErrMsg_TCL_DECLARED
/* 23 */
EXTERN int		NsfErrMsg(Tcl_Interp *interp, char *msg,
				Tcl_FreeProc *type);
#endif
#ifndef NsfVarErrMsg_TCL_DECLARED
#define NsfVarErrMsg_TCL_DECLARED
/* 24 */
EXTERN int		NsfVarErrMsg(Tcl_Interp *interp, ...);
#endif
#ifndef NsfErrInProc_TCL_DECLARED
#define NsfErrInProc_TCL_DECLARED
/* 25 */
EXTERN int		NsfErrInProc(Tcl_Interp *interp, Tcl_Obj *objName,
				Tcl_Obj *clName, CONST char *procName);
#endif
/* Slot 26 is reserved */
#ifndef NsfErrBadVal__TCL_DECLARED
#define NsfErrBadVal__TCL_DECLARED
/* 27 */
EXTERN int		NsfErrBadVal_(Tcl_Interp *interp, char *expected,
				char *value);
#endif
#ifndef NsfObjErrType_TCL_DECLARED
#define NsfObjErrType_TCL_DECLARED
/* 28 */
EXTERN int		NsfObjErrType(Tcl_Interp *interp, Tcl_Obj *nm,
				char *wt, char *parameterName);
#endif
#ifndef NsfStackDump_TCL_DECLARED
#define NsfStackDump_TCL_DECLARED
/* 29 */
EXTERN void		NsfStackDump(Tcl_Interp *interp);
#endif
/* Slot 30 is reserved */
/* Slot 31 is reserved */
#ifndef NsfSetObjClientData_TCL_DECLARED
#define NsfSetObjClientData_TCL_DECLARED
/* 32 */
EXTERN void		NsfSetObjClientData(Nsf_Object *obj,
				ClientData data);
#endif
#ifndef NsfGetObjClientData_TCL_DECLARED
#define NsfGetObjClientData_TCL_DECLARED
/* 33 */
EXTERN ClientData	NsfGetObjClientData(Nsf_Object *obj);
#endif
#ifndef NsfSetClassClientData_TCL_DECLARED
#define NsfSetClassClientData_TCL_DECLARED
/* 34 */
EXTERN void		NsfSetClassClientData(Nsf_Class *cl,
				ClientData data);
#endif
#ifndef NsfGetClassClientData_TCL_DECLARED
#define NsfGetClassClientData_TCL_DECLARED
/* 35 */
EXTERN ClientData	NsfGetClassClientData(Nsf_Class *cl);
#endif
#ifndef NsfRequireObjNamespace_TCL_DECLARED
#define NsfRequireObjNamespace_TCL_DECLARED
/* 36 */
EXTERN void		NsfRequireObjNamespace(Tcl_Interp *interp,
				Nsf_Object *obj);
#endif
#ifndef NsfErrBadVal_TCL_DECLARED
#define NsfErrBadVal_TCL_DECLARED
/* 37 */
EXTERN int		NsfErrBadVal(Tcl_Interp *interp, char *context,
				char *expected, CONST char *value);
#endif
#ifndef NsfNextObjCmd_TCL_DECLARED
#define NsfNextObjCmd_TCL_DECLARED
/* 38 */
EXTERN int		NsfNextObjCmd(ClientData cd, Tcl_Interp *interp,
				int objc, Tcl_Obj *CONST objv[]);
#endif
#ifndef NsfCallMethodWithArgs_TCL_DECLARED
#define NsfCallMethodWithArgs_TCL_DECLARED
/* 39 */
EXTERN int		NsfCallMethodWithArgs(ClientData cd,
				Tcl_Interp *interp, Tcl_Obj *method,
				Tcl_Obj *arg, int objc,
				Tcl_Obj *CONST objv[], int flags);
#endif
#ifndef NsfObjErrArgCnt_TCL_DECLARED
#define NsfObjErrArgCnt_TCL_DECLARED
/* 40 */
EXTERN int		NsfObjErrArgCnt(Tcl_Interp *interp,
				Tcl_Obj *cmdName, Tcl_Obj *methodName,
				char *arglist);
#endif
#ifndef NsfAddObjectMethod_TCL_DECLARED
#define NsfAddObjectMethod_TCL_DECLARED
/* 41 */
EXTERN int		NsfAddObjectMethod(Tcl_Interp *interp,
				struct Nsf_Object *obj, CONST char *nm,
				Tcl_ObjCmdProc *proc, ClientData cd,
				Tcl_CmdDeleteProc *dp, int flags);
#endif
#ifndef NsfAddClassMethod_TCL_DECLARED
#define NsfAddClassMethod_TCL_DECLARED
/* 42 */
EXTERN int		NsfAddClassMethod(Tcl_Interp *interp,
				struct Nsf_Class *cl, CONST char *nm,
				Tcl_ObjCmdProc *proc, ClientData cd,
				Tcl_CmdDeleteProc *dp, int flags);
#endif
#ifndef NsfCreate_TCL_DECLARED
#define NsfCreate_TCL_DECLARED
/* 43 */
EXTERN int		NsfCreate(Tcl_Interp *in, Nsf_Class *class,
				Tcl_Obj *name, ClientData data, int objc,
				Tcl_Obj *CONST objv[]);
#endif

typedef struct NsfStubHooks {
    struct NsfIntStubs *nsfIntStubs;
} NsfStubHooks;

typedef struct NsfStubs {
    int magic;
    struct NsfStubHooks *hooks;

    int (*nsf_Init) (Tcl_Interp *interp); /* 0 */
    void *reserved1;
    struct Nsf_Class * (*xOTclIsClass) (Tcl_Interp *interp, ClientData cd); /* 2 */
    void *reserved3;
    struct Nsf_Object * (*xOTclGetObject) (Tcl_Interp *interp, CONST char *name); /* 4 */
    struct Nsf_Class * (*xOTclGetClass) (Tcl_Interp *interp, CONST char *name); /* 5 */
    int (*xOTclCreateObject) (Tcl_Interp *interp, Tcl_Obj *name, struct Nsf_Class *cl); /* 6 */
    void *reserved7;
    void *reserved8;
    int (*xOTclDeleteObject) (Tcl_Interp *interp, struct Nsf_Object *obj); /* 9 */
    void *reserved10;
    void *reserved11;
    void *reserved12;
    int (*xOTclRemoveObjectMethod) (Tcl_Interp *interp, struct Nsf_Object *obj, CONST char *nm); /* 13 */
    int (*xOTclRemoveClassMethod) (Tcl_Interp *interp, struct Nsf_Class *cl, CONST char *nm); /* 14 */
    Tcl_Obj * (*xOTclOSetInstVar) (struct Nsf_Object *obj, Tcl_Interp *interp, Tcl_Obj *name, Tcl_Obj *value, int flgs); /* 15 */
    Tcl_Obj * (*xOTclOGetInstVar) (struct Nsf_Object *obj, Tcl_Interp *interp, Tcl_Obj *name, int flgs); /* 16 */
    void *reserved17;
    void *reserved18;
    Tcl_Obj * (*xOTcl_ObjSetVar2) (struct Nsf_Object *obj, Tcl_Interp *interp, Tcl_Obj *name1, Tcl_Obj *name2, Tcl_Obj *value, int flgs); /* 19 */
    Tcl_Obj * (*xOTcl_ObjGetVar2) (struct Nsf_Object *obj, Tcl_Interp *interp, Tcl_Obj *name1, Tcl_Obj *name2, int flgs); /* 20 */
    int (*xOTclUnsetInstVar2) (struct Nsf_Object *obj, Tcl_Interp *interp, CONST char *name1, CONST char *name2, int flgs); /* 21 */
    void *reserved22;
    int (*xOTclErrMsg) (Tcl_Interp *interp, char *msg, Tcl_FreeProc *type); /* 23 */
    int (*xOTclVarErrMsg) (Tcl_Interp *interp, ...); /* 24 */
    int (*xOTclErrInProc) (Tcl_Interp *interp, Tcl_Obj *objName, Tcl_Obj *clName, CONST char *procName); /* 25 */
    void *reserved26;
    int (*xOTclErrBadVal_) (Tcl_Interp *interp, char *expected, char *value); /* 27 */
    int (*xOTclObjErrType) (Tcl_Interp *interp, Tcl_Obj *nm, char *wt, char *parameterName); /* 28 */
    void (*xOTclStackDump) (Tcl_Interp *interp); /* 29 */
    void *reserved30;
    void *reserved31;
    void (*xOTclSetObjClientData) (Nsf_Object *obj, ClientData data); /* 32 */
    ClientData (*xOTclGetObjClientData) (Nsf_Object *obj); /* 33 */
    void (*xOTclSetClassClientData) (Nsf_Class *cl, ClientData data); /* 34 */
    ClientData (*xOTclGetClassClientData) (Nsf_Class *cl); /* 35 */
    void (*xOTclRequireObjNamespace) (Tcl_Interp *interp, Nsf_Object *obj); /* 36 */
    int (*xOTclErrBadVal) (Tcl_Interp *interp, char *context, char *expected, CONST char *value); /* 37 */
    int (*xOTclNextObjCmd) (ClientData cd, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]); /* 38 */
    int (*xOTclCallMethodWithArgs) (ClientData cd, Tcl_Interp *interp, Tcl_Obj *method, Tcl_Obj *arg, int objc, Tcl_Obj *CONST objv[], int flags); /* 39 */
    int (*xOTclObjErrArgCnt) (Tcl_Interp *interp, Tcl_Obj *cmdName, Tcl_Obj *methodName, char *arglist); /* 40 */
    int (*xOTclAddObjectMethod) (Tcl_Interp *interp, struct Nsf_Object *obj, CONST char *nm, Tcl_ObjCmdProc *proc, ClientData cd, Tcl_CmdDeleteProc *dp, int flags); /* 41 */
    int (*xOTclAddClassMethod) (Tcl_Interp *interp, struct Nsf_Class *cl, CONST char *nm, Tcl_ObjCmdProc *proc, ClientData cd, Tcl_CmdDeleteProc *dp, int flags); /* 42 */
    int (*xOTclCreate) (Tcl_Interp *in, Nsf_Class *class, Tcl_Obj *name, ClientData data, int objc, Tcl_Obj *CONST objv[]); /* 43 */
} NsfStubs;

#ifdef __cplusplus
extern "C" {
#endif
extern NsfStubs *nsfStubsPtr;
#ifdef __cplusplus
}
#endif

#if defined(USE_NSF_STUBS) && !defined(USE_NSF_STUB_PROCS)

/*
 * Inline function declarations:
 */

#ifndef Nsf_Init
#define Nsf_Init \
	(nsfStubsPtr->nsf_Init) /* 0 */
#endif
/* Slot 1 is reserved */
#ifndef NsfIsClass
#define NsfIsClass \
	(nsfStubsPtr->xOTclIsClass) /* 2 */
#endif
/* Slot 3 is reserved */
#ifndef NsfGetObject
#define NsfGetObject \
	(nsfStubsPtr->xOTclGetObject) /* 4 */
#endif
#ifndef NsfGetClass
#define NsfGetClass \
	(nsfStubsPtr->xOTclGetClass) /* 5 */
#endif
#ifndef NsfCreateObject
#define NsfCreateObject \
	(nsfStubsPtr->xOTclCreateObject) /* 6 */
#endif
/* Slot 7 is reserved */
/* Slot 8 is reserved */
#ifndef NsfDeleteObject
#define NsfDeleteObject \
	(nsfStubsPtr->xOTclDeleteObject) /* 9 */
#endif
/* Slot 10 is reserved */
/* Slot 11 is reserved */
/* Slot 12 is reserved */
#ifndef NsfRemoveObjectMethod
#define NsfRemoveObjectMethod \
	(nsfStubsPtr->xOTclRemoveObjectMethod) /* 13 */
#endif
#ifndef NsfRemoveClassMethod
#define NsfRemoveClassMethod \
	(nsfStubsPtr->xOTclRemoveClassMethod) /* 14 */
#endif
#ifndef NsfOSetInstVar
#define NsfOSetInstVar \
	(nsfStubsPtr->xOTclOSetInstVar) /* 15 */
#endif
#ifndef NsfOGetInstVar
#define NsfOGetInstVar \
	(nsfStubsPtr->xOTclOGetInstVar) /* 16 */
#endif
/* Slot 17 is reserved */
/* Slot 18 is reserved */
#ifndef Nsf_ObjSetVar2
#define Nsf_ObjSetVar2 \
	(nsfStubsPtr->xOTcl_ObjSetVar2) /* 19 */
#endif
#ifndef Nsf_ObjGetVar2
#define Nsf_ObjGetVar2 \
	(nsfStubsPtr->xOTcl_ObjGetVar2) /* 20 */
#endif
#ifndef NsfUnsetInstVar2
#define NsfUnsetInstVar2 \
	(nsfStubsPtr->xOTclUnsetInstVar2) /* 21 */
#endif
/* Slot 22 is reserved */
#ifndef NsfErrMsg
#define NsfErrMsg \
	(nsfStubsPtr->xOTclErrMsg) /* 23 */
#endif
#ifndef NsfVarErrMsg
#define NsfVarErrMsg \
	(nsfStubsPtr->xOTclVarErrMsg) /* 24 */
#endif
#ifndef NsfErrInProc
#define NsfErrInProc \
	(nsfStubsPtr->xOTclErrInProc) /* 25 */
#endif
/* Slot 26 is reserved */
#ifndef NsfErrBadVal_
#define NsfErrBadVal_ \
	(nsfStubsPtr->xOTclErrBadVal_) /* 27 */
#endif
#ifndef NsfObjErrType
#define NsfObjErrType \
	(nsfStubsPtr->xOTclObjErrType) /* 28 */
#endif
#ifndef NsfStackDump
#define NsfStackDump \
	(nsfStubsPtr->xOTclStackDump) /* 29 */
#endif
/* Slot 30 is reserved */
/* Slot 31 is reserved */
#ifndef NsfSetObjClientData
#define NsfSetObjClientData \
	(nsfStubsPtr->xOTclSetObjClientData) /* 32 */
#endif
#ifndef NsfGetObjClientData
#define NsfGetObjClientData \
	(nsfStubsPtr->xOTclGetObjClientData) /* 33 */
#endif
#ifndef NsfSetClassClientData
#define NsfSetClassClientData \
	(nsfStubsPtr->xOTclSetClassClientData) /* 34 */
#endif
#ifndef NsfGetClassClientData
#define NsfGetClassClientData \
	(nsfStubsPtr->xOTclGetClassClientData) /* 35 */
#endif
#ifndef NsfRequireObjNamespace
#define NsfRequireObjNamespace \
	(nsfStubsPtr->xOTclRequireObjNamespace) /* 36 */
#endif
#ifndef NsfErrBadVal
#define NsfErrBadVal \
	(nsfStubsPtr->xOTclErrBadVal) /* 37 */
#endif
#ifndef NsfNextObjCmd
#define NsfNextObjCmd \
	(nsfStubsPtr->xOTclNextObjCmd) /* 38 */
#endif
#ifndef NsfCallMethodWithArgs
#define NsfCallMethodWithArgs \
	(nsfStubsPtr->xOTclCallMethodWithArgs) /* 39 */
#endif
#ifndef NsfObjErrArgCnt
#define NsfObjErrArgCnt \
	(nsfStubsPtr->xOTclObjErrArgCnt) /* 40 */
#endif
#ifndef NsfAddObjectMethod
#define NsfAddObjectMethod \
	(nsfStubsPtr->xOTclAddObjectMethod) /* 41 */
#endif
#ifndef NsfAddClassMethod
#define NsfAddClassMethod \
	(nsfStubsPtr->xOTclAddClassMethod) /* 42 */
#endif
#ifndef NsfCreate
#define NsfCreate \
	(nsfStubsPtr->xOTclCreate) /* 43 */
#endif

#endif /* defined(USE_NSF_STUBS) && !defined(USE_NSF_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* _XOTCLDECLS */

