/* 
 * nxStubInit.c --
 *
 *	This file contains the initializers for the XOTcl stub vectors.
 *
 * Copyright (c) 1998-1999 by XXX
 *
 * See the file "tcl-license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#include "nsfInt.h"

/*
 * Remove macros that will interfere with the definitions below.
 */

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/tcl.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

NsfIntStubs nsfIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
};

static NsfStubHooks nsfStubHooks = {
    &nsfIntStubs
};

NsfStubs nsfStubs = {
    TCL_STUB_MAGIC,
    &nsfStubHooks,
    Nsf_Init, /* 0 */
    NULL, /* 1 */
    NsfIsClass, /* 2 */
    NsfGetObject, /* 3 */
    NsfGetClass, /* 4 */
    NsfCreateObject, /* 5 */
    NsfDeleteObject, /* 6 */
    NsfRemoveObjectMethod, /* 7 */
    NsfRemoveClassMethod, /* 8 */
    NsfOSetInstVar, /* 9 */
    NsfOGetInstVar, /* 10 */
    Nsf_ObjSetVar2, /* 11 */
    Nsf_ObjGetVar2, /* 12 */
    NsfUnsetInstVar2, /* 13 */
    NsfDStringPrintf, /* 14 */
    NsfPrintError, /* 15 */
    NsfErrInProc, /* 16 */
    NsfObjErrType, /* 17 */
    NsfStackDump, /* 18 */
    NsfSetObjClientData, /* 19 */
    NsfGetObjClientData, /* 20 */
    NsfSetClassClientData, /* 21 */
    NsfGetClassClientData, /* 22 */
    NsfRequireObjNamespace, /* 23 */
    NsfErrBadVal, /* 24 */
    NsfNextObjCmd, /* 25 */
    NsfCallMethodWithArgs, /* 26 */
    NsfObjErrArgCnt, /* 27 */
    NsfAddObjectMethod, /* 28 */
    NsfAddClassMethod, /* 29 */
    NsfCreate, /* 30 */
};

/* !END!: Do not edit above this line. */

MODULE_SCOPE const NsfStubs * const nsfConstStubPtr;
const NsfStubs * const nsfConstStubPtr = &nsfStubs;
